server:
  port: 8080

teleEnv: local

spring:
  application:
    name: cloudVendor-demo

  datasource:
    url: jdbc:mysql://localhost:3306/cloud_vendor?useSSL=false&serverTimezone=UTC
    username: root
    password: Raja_1800pw
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 10
      idle-timeout: 30000
      max-lifetime: 600000
      connection-timeout: 30000

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        transaction:
          jta:
            platform: org.hibernate.engine.transaction.jta.platform.internal.NoJtaPlatform
